<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '303b75b314d614af4592ebb02e166e13',
  'DATABASE_URL' => 'mysql://root:955763@127.0.0.1:3306/codi_ejamtest?serverVersion=5.7',
    'SENTRY_DSN' => '',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => '7799d2970757965eec22e739eb0d73fdc68d05fec942cc3a037f5564fdb2c962',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
  'MAILER_DSN'=>'smtps://noreply%40temposoft.cl:sG51D%3C%5DfIw0%5DGkb@mail.temposoft.cl:465',
'MAILER_URL'=>'smtp://mail.temposoft.cl:465?encryption=ssl&auth_mode=login&username=noreply@temposoft.cl&password=sG51D<]fIw0]Gkb',
'RECAPTCHA_SITE_KEY'=>'6Lfut7wsAAAAAF2HityHjQBdYyIill2HbU69lXKw',
'RECAPTCHA_SECRET_KEY'=>'6Lfut7wsAAAAACfNXdCLTzPWFwtQs1wSNV5h1fP1'
);