<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251008215123 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE actuacion (id INT AUTO_INCREMENT NOT NULL, cuaderno_id INT NOT NULL, nombre VARCHAR(255) NOT NULL, INDEX IDX_321583D3EE4BC97C (cuaderno_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE actuacion_anexo_procesal (id INT AUTO_INCREMENT NOT NULL, actuacion_id INT NOT NULL, anexo_procesal_id INT NOT NULL, INDEX IDX_7C63AABB94FD6108 (actuacion_id), INDEX IDX_7C63AABB223672E3 (anexo_procesal_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE anexo_procesal (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contrato_casetracking (id INT AUTO_INCREMENT NOT NULL, contrato_id INT NOT NULL, materia_id INT DEFAULT NULL, nombre_archivo VARCHAR(255) NOT NULL, usuario_carga VARCHAR(255) DEFAULT NULL, fecha_subida DATETIME DEFAULT NULL, INDEX IDX_60E9F46A70AE7BF1 (contrato_id), INDEX IDX_60E9F46AB54DBBCB (materia_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contrato_tramitador (id INT AUTO_INCREMENT NOT NULL, tramitadores_id INT NOT NULL, contrato_id INT NOT NULL, INDEX IDX_2A61EFE174A468AF (tramitadores_id), INDEX IDX_2A61EFE170AE7BF1 (contrato_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cuaderno (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE detalle_cuaderno (id INT AUTO_INCREMENT NOT NULL, cuaderno_id INT NOT NULL, actuacion_id INT NOT NULL, anexo_procesal_id INT DEFAULT NULL, causa_id INT NOT NULL, usuario_creacion_id INT NOT NULL, fecha_creacion DATETIME NOT NULL, INDEX IDX_8FB7FE14EE4BC97C (cuaderno_id), INDEX IDX_8FB7FE1494FD6108 (actuacion_id), INDEX IDX_8FB7FE14223672E3 (anexo_procesal_id), INDEX IDX_8FB7FE14E980B549 (causa_id), INDEX IDX_8FB7FE14AEADF654 (usuario_creacion_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE movatec_log (id INT AUTO_INCREMENT NOT NULL, agenda_id INT DEFAULT NULL, fecha_registro DATETIME NOT NULL, request VARCHAR(255) DEFAULT NULL, response VARCHAR(255) DEFAULT NULL, exito TINYINT(1) DEFAULT NULL, INDEX IDX_324FE63BEA67784A (agenda_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE primera_cuota (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE producto (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reportes (id INT AUTO_INCREMENT NOT NULL, usuario_id INT NOT NULL, fecha_registro DATETIME NOT NULL, criterio JSON DEFAULT NULL, resultado JSON DEFAULT NULL, INDEX IDX_1D1D064DB38439E (usuario_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ticket_tipo (id INT AUTO_INCREMENT NOT NULL, nombre VARCHAR(50) NOT NULL, orden INT DEFAULT NULL, color_badge VARCHAR(20) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vw_causas_activas_final (id_causa INT AUTO_INCREMENT NOT NULL, cuenta_id INT DEFAULT NULL, compaã±ia VARCHAR(255) DEFAULT NULL, contrato_id INT DEFAULT NULL, agenda_id INT DEFAULT NULL, folio INT DEFAULT NULL, fecha_cto DATETIME DEFAULT NULL, cliente VARCHAR(255) DEFAULT NULL, tramitador_id INT DEFAULT NULL, tramitador VARCHAR(255) DEFAULT NULL, abogado_id INT DEFAULT NULL, cerrador VARCHAR(255) DEFAULT NULL, caratulado VARCHAR(255) DEFAULT NULL, folio_activo VARCHAR(255) DEFAULT NULL, vigencia_activo INT DEFAULT NULL, meses_activo INT DEFAULT NULL, fecha_creacion_anexo DATETIME DEFAULT NULL, vigencia_anexo INT DEFAULT NULL, morosos VARCHAR(255) DEFAULT NULL, vip_mayor2_mm VARCHAR(255) DEFAULT NULL, vip_referidos VARCHAR(255) DEFAULT NULL, vip_una_cuota VARCHAR(255) DEFAULT NULL, rol VARCHAR(255) DEFAULT NULL, fecha_registro_observacion DATETIME DEFAULT NULL, activo INT DEFAULT NULL, moroso INT DEFAULT NULL, vip INT DEFAULT NULL, tiene_rol INT DEFAULT NULL, causa_finalizada INT DEFAULT NULL, cuenta_nombre VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id_causa)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vw_clientes_activos_final (id_causa INT AUTO_INCREMENT NOT NULL, cuenta_id INT DEFAULT NULL, compaã±ia VARCHAR(255) DEFAULT NULL, contrato_id INT DEFAULT NULL, agenda_id INT DEFAULT NULL, folio INT DEFAULT NULL, fecha_cto DATETIME DEFAULT NULL, cliente VARCHAR(255) DEFAULT NULL, tramitador_id INT DEFAULT NULL, tramitador VARCHAR(255) DEFAULT NULL, abogado_id INT DEFAULT NULL, cerrador VARCHAR(255) DEFAULT NULL, caratulado VARCHAR(255) DEFAULT NULL, folio_activo VARCHAR(255) DEFAULT NULL, vigencia_activo INT DEFAULT NULL, meses_activo INT DEFAULT NULL, fecha_creacion_anexo DATETIME DEFAULT NULL, vigencia_anexo INT DEFAULT NULL, morosos VARCHAR(255) DEFAULT NULL, vip_mayor2_mm VARCHAR(255) DEFAULT NULL, vip_referidos VARCHAR(255) DEFAULT NULL, vip_una_cuota VARCHAR(255) DEFAULT NULL, rol VARCHAR(255) DEFAULT NULL, fecha_registro_observacion DATETIME DEFAULT NULL, activo INT DEFAULT NULL, moroso INT DEFAULT NULL, vip INT DEFAULT NULL, tiene_rol INT DEFAULT NULL, causa_finalizada INT DEFAULT NULL, cuenta_nombre VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id_causa)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vw_contrato (id INT AUTO_INCREMENT NOT NULL, estado_civil_id INT DEFAULT NULL, situacion_laboral_id INT DEFAULT NULL, estrategia_juridica_id INT DEFAULT NULL, escritura_id INT DEFAULT NULL, agenda_id INT DEFAULT NULL, sucursal_id INT DEFAULT NULL, tramitador_id INT DEFAULT NULL, cliente_id INT DEFAULT NULL, pais_id INT DEFAULT NULL, vehiculo_id INT DEFAULT NULL, vivienda_id INT DEFAULT NULL, reunion_id INT DEFAULT NULL, id_lote_id INT DEFAULT NULL, ccomuna_id INT DEFAULT NULL, cciudad_id INT DEFAULT NULL, cregion_id INT DEFAULT NULL, cartera_id INT DEFAULT NULL, grupo_id INT DEFAULT NULL, estado_encuesta_id INT DEFAULT NULL, nombre VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, telefono VARCHAR(255) NOT NULL, ciudad VARCHAR(255) DEFAULT NULL, rut VARCHAR(255) DEFAULT NULL, direccion VARCHAR(255) NOT NULL, comuna VARCHAR(255) NOT NULL, titulo_contrato VARCHAR(255) DEFAULT NULL, monto_nivel_deuda NUMERIC(10, 0) DEFAULT NULL, monto_contrato NUMERIC(10, 0) DEFAULT NULL, cuotas INT DEFAULT NULL, valor_cuota NUMERIC(10, 0) DEFAULT NULL, interes NUMERIC(5, 2) DEFAULT NULL, dia_pago INT DEFAULT NULL, fecha_creacion DATETIME DEFAULT NULL, clave_unica VARCHAR(255) DEFAULT NULL, telefono_recado VARCHAR(255) DEFAULT NULL, fecha_primer_pago DATETIME DEFAULT NULL, primera_cuota DOUBLE PRECISION DEFAULT NULL, fecha_primera_cuota DATE DEFAULT NULL, pdf VARCHAR(255) DEFAULT NULL, observacion LONGTEXT DEFAULT NULL, is_abono TINYINT(1) DEFAULT NULL, fecha_ultimo_pago DATE DEFAULT NULL, is_finalizado TINYINT(1) DEFAULT NULL, lote INT DEFAULT NULL, pdf_termino VARCHAR(255) DEFAULT NULL, fecha_termino DATETIME DEFAULT NULL, vigencia INT DEFAULT NULL, fecha_desiste DATETIME DEFAULT NULL, fecha_pdf_anexo DATETIME DEFAULT NULL, ultima_funcion VARCHAR(255) DEFAULT NULL, q_mov INT DEFAULT NULL, fecha_compromiso DATE DEFAULT NULL, folio VARCHAR(255) DEFAULT NULL, folio_contrato VARCHAR(255) DEFAULT NULL, sexo VARCHAR(20) DEFAULT NULL, is_anexo TINYINT(1) DEFAULT NULL, proximo_vencimiento DATE DEFAULT NULL, fecha_ultima_gestion DATE DEFAULT NULL, pago_actual NUMERIC(10, 0) DEFAULT NULL, is_total TINYINT(1) DEFAULT NULL, cartera_orden INT NOT NULL, is_incorporacion TINYINT(1) DEFAULT NULL, observacion_encuesta VARCHAR(255) NOT NULL, fecha_encuesta DATETIME NOT NULL, fecha_gestion DATETIME NOT NULL, qty_encuesta INT DEFAULT NULL, qty_gestion_encuesta INT DEFAULT NULL, ultima_nota INT DEFAULT NULL, usuario_encuesta_id INT DEFAULT NULL, usuario_gestion_id INT DEFAULT NULL, usuario_calidad VARCHAR(255) NOT NULL, encuesta_funcion_encuesta VARCHAR(255) NOT NULL, encuesta_funcion_respuesta VARCHAR(255) NOT NULL, gestion_funcion_encuesta VARCHAR(255) NOT NULL, gestion_funcion_respuesta VARCHAR(255) NOT NULL, gestion_observacion VARCHAR(255) NOT NULL, encuesta_observacion VARCHAR(255) NOT NULL, encuesta_nota VARCHAR(255) NOT NULL, encuesta_fecha_cierre DATETIME NOT NULL, encuesta_respuesta_abierta VARCHAR(255) NOT NULL, encuesta_pregunta VARCHAR(255) NOT NULL, fecha_pago DATETIME NOT NULL, monto INT DEFAULT NULL, numero INT DEFAULT NULL, vip INT DEFAULT NULL, INDEX IDX_C725835075376D93 (estado_civil_id), INDEX IDX_C72583508577D28 (situacion_laboral_id), INDEX IDX_C725835062144410 (estrategia_juridica_id), INDEX IDX_C72583505D855194 (escritura_id), UNIQUE INDEX UNIQ_C7258350EA67784A (agenda_id), INDEX IDX_C7258350279A5D5E (sucursal_id), INDEX IDX_C72583502D21BFE2 (tramitador_id), INDEX IDX_C7258350DE734E51 (cliente_id), INDEX IDX_C7258350C604D5C6 (pais_id), INDEX IDX_C725835025F7D575 (vehiculo_id), INDEX IDX_C725835081A75788 (vivienda_id), INDEX IDX_C72583504E9B7368 (reunion_id), UNIQUE INDEX UNIQ_C72583506FEFB00C (id_lote_id), INDEX IDX_C725835038692C4C (ccomuna_id), INDEX IDX_C7258350D73341BF (cciudad_id), INDEX IDX_C7258350A775C2FE (cregion_id), INDEX IDX_C7258350A5A18135 (cartera_id), INDEX IDX_C72583509C833003 (grupo_id), INDEX IDX_C72583507C88A2F6 (estado_encuesta_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vw_resumen_causas (tramitador_id INT AUTO_INCREMENT NOT NULL, cuenta_id INT DEFAULT NULL, tramitador VARCHAR(255) DEFAULT NULL, causas_activas INT NOT NULL, causas_al_dia INT NOT NULL, clientes_activos INT NOT NULL, clientes_al_dia INT NOT NULL, clientes_morosos INT NOT NULL, clientes_activos_vip INT NOT NULL, clientes_al_dia_vip INT NOT NULL, causas_activas_con_rol INT NOT NULL, causas_activas_sin_rol INT NOT NULL, causas_activas_finalizadas INT NOT NULL, PRIMARY KEY(tramitador_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE actuacion ADD CONSTRAINT FK_321583D3EE4BC97C FOREIGN KEY (cuaderno_id) REFERENCES cuaderno (id)');
        $this->addSql('ALTER TABLE actuacion_anexo_procesal ADD CONSTRAINT FK_7C63AABB94FD6108 FOREIGN KEY (actuacion_id) REFERENCES actuacion (id)');
        $this->addSql('ALTER TABLE actuacion_anexo_procesal ADD CONSTRAINT FK_7C63AABB223672E3 FOREIGN KEY (anexo_procesal_id) REFERENCES anexo_procesal (id)');
        $this->addSql('ALTER TABLE contrato_casetracking ADD CONSTRAINT FK_60E9F46A70AE7BF1 FOREIGN KEY (contrato_id) REFERENCES contrato (id)');
        $this->addSql('ALTER TABLE contrato_casetracking ADD CONSTRAINT FK_60E9F46AB54DBBCB FOREIGN KEY (materia_id) REFERENCES materia (id)');
        $this->addSql('ALTER TABLE contrato_tramitador ADD CONSTRAINT FK_2A61EFE174A468AF FOREIGN KEY (tramitadores_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE contrato_tramitador ADD CONSTRAINT FK_2A61EFE170AE7BF1 FOREIGN KEY (contrato_id) REFERENCES contrato (id)');
        $this->addSql('ALTER TABLE detalle_cuaderno ADD CONSTRAINT FK_8FB7FE14EE4BC97C FOREIGN KEY (cuaderno_id) REFERENCES cuaderno (id)');
        $this->addSql('ALTER TABLE detalle_cuaderno ADD CONSTRAINT FK_8FB7FE1494FD6108 FOREIGN KEY (actuacion_id) REFERENCES actuacion (id)');
        $this->addSql('ALTER TABLE detalle_cuaderno ADD CONSTRAINT FK_8FB7FE14223672E3 FOREIGN KEY (anexo_procesal_id) REFERENCES anexo_procesal (id)');
        $this->addSql('ALTER TABLE detalle_cuaderno ADD CONSTRAINT FK_8FB7FE14E980B549 FOREIGN KEY (causa_id) REFERENCES causa (id)');
        $this->addSql('ALTER TABLE detalle_cuaderno ADD CONSTRAINT FK_8FB7FE14AEADF654 FOREIGN KEY (usuario_creacion_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE movatec_log ADD CONSTRAINT FK_324FE63BEA67784A FOREIGN KEY (agenda_id) REFERENCES agenda (id)');
        $this->addSql('ALTER TABLE reportes ADD CONSTRAINT FK_1D1D064DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE vw_contrato ADD CONSTRAINT FK_C725835075376D93 FOREIGN KEY (estado_civil_id) REFERENCES estado_civil (id)');
        $this->addSql('ALTER TABLE vw_contrato ADD CONSTRAINT FK_C72583508577D28 FOREIGN KEY (situacion_laboral_id) REFERENCES situacion_laboral (id)');
        $this->addSql('ALTER TABLE vw_contrato ADD CONSTRAINT FK_C725835062144410 FOREIGN KEY (estrategia_juridica_id) REFERENCES estrategia_juridica (id)');
        $this->addSql('ALTER TABLE vw_contrato ADD CONSTRAINT FK_C72583505D855194 FOREIGN KEY (escritura_id) REFERENCES escritura (id)');
        $this->addSql('ALTER TABLE vw_contrato ADD CONSTRAINT FK_C7258350EA67784A FOREIGN KEY (agenda_id) REFERENCES agenda (id)');
        $this->addSql('ALTER TABLE vw_contrato ADD CONSTRAINT FK_C7258350279A5D5E FOREIGN KEY (sucursal_id) REFERENCES sucursal (id)');
        $this->addSql('ALTER TABLE vw_contrato ADD CONSTRAINT FK_C72583502D21BFE2 FOREIGN KEY (tramitador_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE vw_contrato ADD CONSTRAINT FK_C7258350DE734E51 FOREIGN KEY (cliente_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE vw_contrato ADD CONSTRAINT FK_C7258350C604D5C6 FOREIGN KEY (pais_id) REFERENCES pais (id)');
        $this->addSql('ALTER TABLE vw_contrato ADD CONSTRAINT FK_C725835025F7D575 FOREIGN KEY (vehiculo_id) REFERENCES contrato_vehiculo (id)');
        $this->addSql('ALTER TABLE vw_contrato ADD CONSTRAINT FK_C725835081A75788 FOREIGN KEY (vivienda_id) REFERENCES contrato_vivienda (id)');
        $this->addSql('ALTER TABLE vw_contrato ADD CONSTRAINT FK_C72583504E9B7368 FOREIGN KEY (reunion_id) REFERENCES reunion (id)');
        $this->addSql('ALTER TABLE vw_contrato ADD CONSTRAINT FK_C72583506FEFB00C FOREIGN KEY (id_lote_id) REFERENCES lotes (id)');
        $this->addSql('ALTER TABLE vw_contrato ADD CONSTRAINT FK_C725835038692C4C FOREIGN KEY (ccomuna_id) REFERENCES comuna (id)');
        $this->addSql('ALTER TABLE vw_contrato ADD CONSTRAINT FK_C7258350D73341BF FOREIGN KEY (cciudad_id) REFERENCES ciudad (id)');
        $this->addSql('ALTER TABLE vw_contrato ADD CONSTRAINT FK_C7258350A775C2FE FOREIGN KEY (cregion_id) REFERENCES region (id)');
        $this->addSql('ALTER TABLE vw_contrato ADD CONSTRAINT FK_C7258350A5A18135 FOREIGN KEY (cartera_id) REFERENCES cartera (id)');
        $this->addSql('ALTER TABLE vw_contrato ADD CONSTRAINT FK_C72583509C833003 FOREIGN KEY (grupo_id) REFERENCES grupo (id)');
        $this->addSql('ALTER TABLE vw_contrato ADD CONSTRAINT FK_C72583507C88A2F6 FOREIGN KEY (estado_encuesta_id) REFERENCES estado_encuesta (id)');
        $this->addSql('DROP TABLE html_tempaltes');
        $this->addSql('DROP TABLE logs');
        $this->addSql('DROP TABLE mails_enviados');
        $this->addSql('ALTER TABLE accion CHANGE empresa_id empresa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE agenda CHANGE cuenta_id cuenta_id INT DEFAULT NULL, CHANGE gestionar_id gestionar_id INT DEFAULT NULL, CHANGE agendador_id agendador_id INT DEFAULT NULL, CHANGE sucursal_id sucursal_id INT DEFAULT NULL, CHANGE status_id status_id INT DEFAULT NULL, CHANGE abogado_id abogado_id INT DEFAULT NULL, CHANGE reunion_id reunion_id INT DEFAULT NULL, CHANGE agenda_contacto_id agenda_contacto_id INT DEFAULT NULL, CHANGE sub_status_id sub_status_id INT DEFAULT NULL, CHANGE nombre_cliente nombre_cliente VARCHAR(255) DEFAULT NULL, CHANGE email_cliente email_cliente VARCHAR(255) DEFAULT NULL, CHANGE telefono_cliente telefono_cliente VARCHAR(255) DEFAULT NULL, CHANGE ciudad_cliente ciudad_cliente VARCHAR(255) DEFAULT NULL, CHANGE fecha_carga fecha_carga DATETIME DEFAULT NULL, CHANGE fecha_asignado fecha_asignado DATETIME DEFAULT NULL, CHANGE monto monto NUMERIC(10, 0) DEFAULT NULL, CHANGE rut_cliente rut_cliente VARCHAR(255) DEFAULT NULL, CHANGE telefono_recado_cliente telefono_recado_cliente VARCHAR(255) DEFAULT NULL, CHANGE fecha_contrato fecha_contrato DATETIME DEFAULT NULL, CHANGE lead lead VARCHAR(255) DEFAULT NULL, CHANGE form_id form_id VARCHAR(255) DEFAULT NULL, CHANGE pago_actual pago_actual NUMERIC(10, 0) DEFAULT NULL, CHANGE canal_id canal_id INT DEFAULT NULL, CHANGE fecha_seguimiento fecha_seguimiento DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE agenda ADD CONSTRAINT FK_2CEDC87768DB5B2E FOREIGN KEY (canal_id) REFERENCES canal (id)');
        $this->addSql('ALTER TABLE agenda RENAME INDEX fk_2cedc8776bf700bd TO IDX_2CEDC8776BF700BD');
        $this->addSql('ALTER TABLE agenda RENAME INDEX fk_2cedc87779fa4603 TO IDX_2CEDC87779FA4603');
        $this->addSql('ALTER TABLE agenda_observacion CHANGE status_id status_id INT DEFAULT NULL, CHANGE sub_status_id sub_status_id INT DEFAULT NULL, CHANGE abogado_destino_id abogado_destino_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE agenda_observacion RENAME INDEX fk_bb64540079fa4603 TO IDX_BB64540079FA4603');
        $this->addSql('ALTER TABLE agenda_observacion RENAME INDEX fk_bb645400cf6bbc1e TO IDX_BB645400CF6BBC1E');
        $this->addSql('ALTER TABLE agenda_status CHANGE orden orden INT DEFAULT NULL, CHANGE icon icon VARCHAR(255) DEFAULT NULL, CHANGE color color VARCHAR(255) DEFAULT NULL, CHANGE vermas vermas TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE agenda_sub_status CHANGE agenda_status_id agenda_status_id INT DEFAULT NULL, CHANGE color color VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE causa ADD causa_finalizada TINYINT(1) DEFAULT NULL, ADD fecha_finalizado DATETIME DEFAULT NULL, CHANGE anexo_id anexo_id INT DEFAULT NULL, CHANGE materia_estrategia_id materia_estrategia_id INT DEFAULT NULL, CHANGE juzgado_cuenta_id juzgado_cuenta_id INT DEFAULT NULL, CHANGE id_causa id_causa VARCHAR(255) DEFAULT NULL, CHANGE causa_nombre causa_nombre VARCHAR(255) NOT NULL, CHANGE estado estado TINYINT(1) DEFAULT NULL, CHANGE fecha_ultimo_ingreso fecha_ultimo_ingreso DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE causa ADD CONSTRAINT FK_F7B7BBA6516A508C FOREIGN KEY (materia_estrategia_id) REFERENCES materia_estrategia (id)');
        $this->addSql('ALTER TABLE causa ADD CONSTRAINT FK_F7B7BBA6AABE9B97 FOREIGN KEY (juzgado_cuenta_id) REFERENCES juzgado_cuenta (id)');
        $this->addSql('ALTER TABLE causa ADD CONSTRAINT FK_F7B7BBA6EA67784A FOREIGN KEY (agenda_id) REFERENCES agenda (id)');
        $this->addSql('ALTER TABLE causa RENAME INDEX fk_f7b7bba6c9348664 TO IDX_F7B7BBA6C9348664');
        $this->addSql('ALTER TABLE causa_observacion ADD detalle_cuaderno_id INT DEFAULT NULL, CHANGE causa_id causa_id INT NOT NULL');
        $this->addSql('ALTER TABLE causa_observacion ADD CONSTRAINT FK_23D9D014A254240F FOREIGN KEY (detalle_cuaderno_id) REFERENCES detalle_cuaderno (id)');
        $this->addSql('CREATE INDEX IDX_23D9D014A254240F ON causa_observacion (detalle_cuaderno_id)');
        $this->addSql('ALTER TABLE ciudad CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE ciudad RENAME INDEX region_id TO IDX_8E86059E98260155');
        $this->addSql('ALTER TABLE cliente_potencial CHANGE form_id form_id INT DEFAULT NULL, CHANGE leadgen_id leadgen_id INT DEFAULT NULL, CHANGE page_id page_id INT DEFAULT NULL, CHANGE created_time created_time INT DEFAULT NULL, CHANGE campos campos JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE cobranza DROP cuota_id, CHANGE funcion_id funcion_id INT DEFAULT NULL, CHANGE respuesta_id respuesta_id INT DEFAULT NULL, CHANGE fecha_compromiso fecha_compromiso DATETIME DEFAULT NULL, CHANGE is_nulo is_nulo TINYINT(1) DEFAULT NULL, CHANGE fecha fecha DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE cobranza ADD CONSTRAINT FK_AE20EF3D70AE7BF1 FOREIGN KEY (contrato_id) REFERENCES contrato (id)');
        $this->addSql('CREATE INDEX IDX_AE20EF3D70AE7BF1 ON cobranza (contrato_id)');
        $this->addSql('ALTER TABLE cobranza_respuesta CHANGE is_fecha_compromiso is_fecha_compromiso TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE comuna DROP FOREIGN KEY comuna_ibfk_1');
        $this->addSql('ALTER TABLE comuna CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE comuna ADD CONSTRAINT FK_7E7DAE49E8608214 FOREIGN KEY (ciudad_id) REFERENCES ciudad (id)');
        $this->addSql('ALTER TABLE comuna RENAME INDEX ciudad_id TO IDX_7E7DAE49E8608214');
        $this->addSql('ALTER TABLE configuracion CHANGE host host VARCHAR(255) DEFAULT NULL, CHANGE lotes lotes INT DEFAULT NULL, CHANGE valor_multa valor_multa INT DEFAULT NULL, CHANGE toku_id toku_id VARCHAR(255) DEFAULT NULL, CHANGE toku_secret toku_secret VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE contrato DROP INDEX FK_666965236FEFB00C, ADD UNIQUE INDEX UNIQ_666965236FEFB00C (id_lote_id)');
        $this->addSql('ALTER TABLE contrato DROP FOREIGN KEY FK_666965236FEFB00C');
        $this->addSql('ALTER TABLE contrato CHANGE estado_civil_id estado_civil_id INT DEFAULT NULL, CHANGE situacion_laboral_id situacion_laboral_id INT DEFAULT NULL, CHANGE estrategia_juridica_id estrategia_juridica_id INT DEFAULT NULL, CHANGE escritura_id escritura_id INT DEFAULT NULL, CHANGE agenda_id agenda_id INT DEFAULT NULL, CHANGE sucursal_id sucursal_id INT DEFAULT NULL, CHANGE tramitador_id tramitador_id INT DEFAULT NULL, CHANGE cliente_id cliente_id INT DEFAULT NULL, CHANGE pais_id pais_id INT DEFAULT NULL, CHANGE vehiculo_id vehiculo_id INT DEFAULT NULL, CHANGE vivienda_id vivienda_id INT DEFAULT NULL, CHANGE reunion_id reunion_id INT DEFAULT NULL, CHANGE id_lote_id id_lote_id INT DEFAULT NULL, CHANGE ccomuna_id ccomuna_id INT DEFAULT NULL, CHANGE cciudad_id cciudad_id INT DEFAULT NULL, CHANGE cregion_id cregion_id INT DEFAULT NULL, CHANGE cartera_id cartera_id INT DEFAULT NULL, CHANGE grupo_id grupo_id INT DEFAULT NULL, CHANGE estado_encuesta_id estado_encuesta_id INT DEFAULT NULL, CHANGE email email VARCHAR(255) DEFAULT NULL, CHANGE ciudad ciudad VARCHAR(255) DEFAULT NULL, CHANGE rut rut VARCHAR(255) DEFAULT NULL, CHANGE comuna comuna VARCHAR(255) NOT NULL, CHANGE titulo_contrato titulo_contrato VARCHAR(255) DEFAULT NULL, CHANGE monto_nivel_deuda monto_nivel_deuda NUMERIC(10, 0) DEFAULT NULL, CHANGE monto_contrato monto_contrato NUMERIC(10, 0) DEFAULT NULL, CHANGE cuotas cuotas INT DEFAULT NULL, CHANGE valor_cuota valor_cuota NUMERIC(10, 0) DEFAULT NULL, CHANGE interes interes NUMERIC(5, 2) DEFAULT NULL, CHANGE dia_pago dia_pago INT DEFAULT NULL, CHANGE fecha_creacion fecha_creacion DATETIME DEFAULT NULL, CHANGE clave_unica clave_unica VARCHAR(255) DEFAULT NULL, CHANGE telefono_recado telefono_recado VARCHAR(255) DEFAULT NULL, CHANGE fecha_primer_pago fecha_primer_pago DATETIME DEFAULT NULL, CHANGE pdf pdf VARCHAR(255) DEFAULT NULL, CHANGE is_abono is_abono TINYINT(1) DEFAULT NULL, CHANGE primera_cuota primera_cuota DOUBLE PRECISION DEFAULT NULL, CHANGE fecha_primera_cuota fecha_primera_cuota DATE DEFAULT NULL, CHANGE fecha_ultimo_pago fecha_ultimo_pago DATE DEFAULT NULL, CHANGE is_finalizado is_finalizado TINYINT(1) DEFAULT NULL, CHANGE lote lote INT DEFAULT NULL, CHANGE pdf_termino pdf_termino VARCHAR(255) DEFAULT NULL, CHANGE fecha_termino fecha_termino DATETIME DEFAULT NULL, CHANGE vigencia vigencia INT DEFAULT NULL, CHANGE fecha_desiste fecha_desiste DATETIME DEFAULT NULL, CHANGE fecha_pdf_anexo fecha_pdf_anexo DATETIME DEFAULT NULL, CHANGE fecha_compromiso fecha_compromiso DATE DEFAULT NULL, CHANGE ultima_funcion ultima_funcion VARCHAR(255) DEFAULT NULL, CHANGE q_mov q_mov INT DEFAULT NULL, CHANGE folio folio VARCHAR(255) DEFAULT NULL, CHANGE sexo sexo VARCHAR(20) DEFAULT NULL, CHANGE is_anexo is_anexo TINYINT(1) DEFAULT NULL, CHANGE proximo_vencimiento proximo_vencimiento DATE DEFAULT NULL, CHANGE fecha_ultima_gestion fecha_ultima_gestion DATE DEFAULT NULL, CHANGE pago_actual pago_actual NUMERIC(10, 0) DEFAULT NULL, CHANGE is_total is_total TINYINT(1) DEFAULT NULL, CHANGE is_incorporacion is_incorporacion TINYINT(1) DEFAULT NULL, CHANGE observacion_encuesta observacion_encuesta VARCHAR(255) NOT NULL, CHANGE fecha_encuesta fecha_encuesta DATETIME NOT NULL, CHANGE qty_encuesta qty_encuesta INT DEFAULT NULL, CHANGE qty_gestion_encuesta qty_gestion_encuesta INT DEFAULT NULL');
        $this->addSql('ALTER TABLE contrato ADD CONSTRAINT FK_666965236FEFB00C FOREIGN KEY (id_lote_id) REFERENCES lotes (id)');
        $this->addSql('ALTER TABLE contrato RENAME INDEX fk_66696523279a5d5e TO IDX_66696523279A5D5E');
        $this->addSql('ALTER TABLE contrato RENAME INDEX fk_66696523a5a18135 TO IDX_66696523A5A18135');
        $this->addSql('ALTER TABLE contrato RENAME INDEX fk_666965237c88a2f6 TO IDX_666965237C88A2F6');
        $this->addSql('ALTER TABLE contrato_anexo ADD usuario_registro_id INT DEFAULT NULL, CHANGE pdf pdf VARCHAR(255) DEFAULT NULL, CHANGE folio folio INT DEFAULT NULL, CHANGE monto_contrato monto_contrato DOUBLE PRECISION DEFAULT NULL, CHANGE is_abono is_abono TINYINT(1) DEFAULT NULL, CHANGE abono abono DOUBLE PRECISION DEFAULT NULL, CHANGE is_total is_total TINYINT(1) DEFAULT NULL, CHANGE n_cuotas n_cuotas INT DEFAULT NULL, CHANGE valor_cuota valor_cuota DOUBLE PRECISION DEFAULT NULL, CHANGE dias_pago dias_pago INT DEFAULT NULL, CHANGE fecha_primer_pago fecha_primer_pago DATE DEFAULT NULL, CHANGE vigencia vigencia INT DEFAULT NULL, CHANGE tipo_anexo tipo_anexo SMALLINT DEFAULT NULL, CHANGE estado estado TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE contrato_anexo ADD CONSTRAINT FK_9DD8C30E1EEFD20 FOREIGN KEY (usuario_registro_id) REFERENCES usuario (id)');
        $this->addSql('CREATE INDEX IDX_9DD8C30E1EEFD20 ON contrato_anexo (usuario_registro_id)');
        $this->addSql('ALTER TABLE contrato_archivos CHANGE causa_id causa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE contrato_mee CHANGE mee_id mee_id INT DEFAULT NULL, CHANGE mees mees LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\'');
        $this->addSql('ALTER TABLE contrato_observacion ADD CONSTRAINT FK_1AA2E2DE1EEFD20 FOREIGN KEY (usuario_registro_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE contrato_observacion ADD CONSTRAINT FK_1AA2E2DE70AE7BF1 FOREIGN KEY (contrato_id) REFERENCES contrato (id)');
        $this->addSql('ALTER TABLE contrato_rol CHANGE juzgado_id juzgado_id INT DEFAULT NULL, CHANGE contrato_id contrato_id INT DEFAULT NULL, CHANGE nombre_rol nombre_rol VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE contrato_vehiculo CHANGE empresa_id empresa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE contrato_vivienda CHANGE empresa_id empresa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE cuenta CHANGE fecha_ultimamodificacion fecha_ultimamodificacion DATETIME DEFAULT NULL, CHANGE page_id page_id DOUBLE PRECISION DEFAULT NULL, CHANGE vigencia_contratos vigencia_contratos INT DEFAULT NULL');
        $this->addSql('ALTER TABLE cuenta_materia CHANGE estado estado TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE cuota CHANGE usuario_anulacion_id usuario_anulacion_id INT DEFAULT NULL, CHANGE anexo_id anexo_id INT DEFAULT NULL, CHANGE pagado pagado INT DEFAULT NULL, CHANGE anular anular TINYINT(1) DEFAULT NULL, CHANGE fecha_anulacion fecha_anulacion DATETIME DEFAULT NULL, CHANGE is_multa is_multa TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE empresa CHANGE rol rol VARCHAR(255) DEFAULT NULL, CHANGE logo logo VARCHAR(255) DEFAULT NULL, CHANGE fecha_ultimamodificacion fecha_ultimamodificacion DATETIME DEFAULT NULL, CHANGE logo_alt logo_alt VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE encuesta CHANGE funcion_encuesta_id funcion_encuesta_id INT DEFAULT NULL, CHANGE funcion_respuesta_id funcion_respuesta_id INT DEFAULT NULL, CHANGE fecha_creacion fecha_creacion DATETIME DEFAULT NULL, CHANGE fecha_pendiente fecha_pendiente DATETIME DEFAULT NULL, CHANGE fecha_cierre fecha_cierre DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE encuesta ADD CONSTRAINT FK_B25B68419F5A440B FOREIGN KEY (estado_id) REFERENCES estado_encuesta (id)');
        $this->addSql('CREATE INDEX IDX_B25B68419F5A440B ON encuesta (estado_id)');
        $this->addSql('ALTER TABLE encuesta_preguntas CHANGE nota nota VARCHAR(255) DEFAULT NULL, CHANGE respuesta_abierta respuesta_abierta VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE escritura CHANGE empresa_id empresa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE estado_civil CHANGE empresa_id empresa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE estrategia_juridica CHANGE empresa_id empresa_id INT DEFAULT NULL, CHANGE linea_tiempo_id linea_tiempo_id INT DEFAULT NULL, CHANGE precio precio DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE importacion CHANGE cuenta_id cuenta_id INT DEFAULT NULL, CHANGE usuario_carga_id usuario_carga_id INT DEFAULT NULL, CHANGE estado estado INT DEFAULT NULL, CHANGE tipo_importacion tipo_importacion INT DEFAULT NULL');
        $this->addSql('ALTER TABLE juzgado CHANGE empresa_id empresa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE juzgado ADD CONSTRAINT FK_695F140E521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE juzgado RENAME INDEX empresa_id TO IDX_695F140E521E1991');
        $this->addSql('ALTER TABLE juzgado_cuenta ADD CONSTRAINT FK_FCE1830F9AEFF118 FOREIGN KEY (cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE juzgado_cuenta ADD CONSTRAINT FK_FCE1830FB9A57363 FOREIGN KEY (juzgado_id) REFERENCES juzgado (id)');
        $this->addSql('ALTER TABLE linea_tiempo CHANGE orden orden INT DEFAULT NULL');
        $this->addSql('ALTER TABLE linea_tiempo_etapas ADD CONSTRAINT FK_6535CAFD63AA8B75 FOREIGN KEY (linea_tiempo_id) REFERENCES linea_tiempo (id)');
        $this->addSql('ALTER TABLE linea_tiempo_terminada ADD CONSTRAINT FK_271DA87BE980B549 FOREIGN KEY (causa_id) REFERENCES causa (id)');
        $this->addSql('ALTER TABLE linea_tiempo_terminada ADD CONSTRAINT FK_271DA87BBCFBDE31 FOREIGN KEY (linea_tiempo_etapas_id) REFERENCES linea_tiempo_etapas (id)');
        $this->addSql('ALTER TABLE linea_tiempo_terminada ADD CONSTRAINT FK_271DA87B1EEFD20 FOREIGN KEY (usuario_registro_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE lotes CHANGE empresa_id empresa_id INT DEFAULT NULL, CHANGE is_asignado is_asignado TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE lotes ADD CONSTRAINT FK_7BDBF5EC521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE materia ADD CONSTRAINT FK_6DF05284521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE materia_estrategia ADD CONSTRAINT FK_8A1D519EB54DBBCB FOREIGN KEY (materia_id) REFERENCES materia (id)');
        $this->addSql('ALTER TABLE materia_estrategia ADD CONSTRAINT FK_8A1D519E62144410 FOREIGN KEY (estrategia_juridica_id) REFERENCES estrategia_juridica (id)');
        $this->addSql('ALTER TABLE mee ADD CONSTRAINT FK_9A1C8B54516A508C FOREIGN KEY (materia_estrategia_id) REFERENCES materia_estrategia (id)');
        $this->addSql('ALTER TABLE mee ADD CONSTRAINT FK_9A1C8B545D855194 FOREIGN KEY (escritura_id) REFERENCES escritura (id)');
        $this->addSql('ALTER TABLE mensaje CHANGE usuario_registro_id usuario_registro_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE mensaje ADD CONSTRAINT FK_9B631D013F7A1974 FOREIGN KEY (mensaje_tipo_id) REFERENCES mensaje_tipo (id)');
        $this->addSql('ALTER TABLE mensaje ADD CONSTRAINT FK_9B631D011EEFD20 FOREIGN KEY (usuario_registro_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE mensaje ADD CONSTRAINT FK_9B631D0117064CB7 FOREIGN KEY (usuario_destino_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE mensaje_tipo CHANGE id id INT AUTO_INCREMENT NOT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE menu CHANGE depende_de_id depende_de_id INT DEFAULT NULL, CHANGE icono icono VARCHAR(255) DEFAULT NULL, CHANGE menu_cabezera_id menu_cabezera_id INT DEFAULT NULL, CHANGE modulo_id modulo_id INT DEFAULT NULL, CHANGE orden orden INT DEFAULT NULL');
        $this->addSql('ALTER TABLE menu ADD CONSTRAINT FK_7D053A93521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE menu ADD CONSTRAINT FK_7D053A93A53F971C FOREIGN KEY (depende_de_id) REFERENCES menu (id)');
        $this->addSql('ALTER TABLE menu ADD CONSTRAINT FK_7D053A93975F194D FOREIGN KEY (menu_cabezera_id) REFERENCES menu_cabezera (id)');
        $this->addSql('ALTER TABLE menu ADD CONSTRAINT FK_7D053A93C07F55F5 FOREIGN KEY (modulo_id) REFERENCES modulo (id)');
        $this->addSql('ALTER TABLE menu_cabezera CHANGE empresa_id empresa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE menu_cabezera ADD CONSTRAINT FK_431A2F13521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE modulo CHANGE nombre_alt nombre_alt VARCHAR(255) DEFAULT NULL, CHANGE descripcion descripcion VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE modulo_per ADD CONSTRAINT FK_ABF22FE5521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE modulo_per ADD CONSTRAINT FK_ABF22FE5C07F55F5 FOREIGN KEY (modulo_id) REFERENCES modulo (id)');
        $this->addSql('ALTER TABLE movimientospjud CHANGE fecha_pjud fecha_pjud DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE pago DROP INDEX contrato_id_2, ADD INDEX IDX_F4DF5F3E70AE7BF1 (contrato_id)');
        $this->addSql('DROP INDEX contrato_id_3 ON pago');
        $this->addSql('DROP INDEX contrato_id ON pago');
        $this->addSql('ALTER TABLE pago DROP fecha_ingreso, CHANGE boleta boleta VARCHAR(255) DEFAULT NULL, CHANGE ncomprobante ncomprobante VARCHAR(255) DEFAULT NULL, CHANGE comprobante comprobante LONGTEXT DEFAULT NULL, CHANGE usuario_anulacion_id usuario_anulacion_id INT DEFAULT NULL, CHANGE anulado anulado TINYINT(1) DEFAULT NULL, CHANGE fecha_anulacion fecha_anulacion DATETIME DEFAULT NULL, CHANGE contrato_id contrato_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE pago ADD CONSTRAINT FK_F4DF5F3EC6690F67 FOREIGN KEY (pago_tipo_id) REFERENCES pago_tipo (id)');
        $this->addSql('ALTER TABLE pago ADD CONSTRAINT FK_F4DF5F3EFF66CCC7 FOREIGN KEY (pago_canal_id) REFERENCES pago_canal (id)');
        $this->addSql('ALTER TABLE pago ADD CONSTRAINT FK_F4DF5F3E1EEFD20 FOREIGN KEY (usuario_registro_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE pago ADD CONSTRAINT FK_F4DF5F3E1FB75A3B FOREIGN KEY (cuenta_corriente_id) REFERENCES cuenta_corriente (id)');
        $this->addSql('ALTER TABLE pago ADD CONSTRAINT FK_F4DF5F3EBAF036CE FOREIGN KEY (usuario_anulacion_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE pago ADD CONSTRAINT FK_F4DF5F3E70AE7BF1 FOREIGN KEY (contrato_id) REFERENCES contrato (id)');
        $this->addSql('ALTER TABLE pago_canal CHANGE empresa_id empresa_id INT DEFAULT NULL, CHANGE estado estado TINYINT(1) DEFAULT NULL, CHANGE orden orden INT DEFAULT NULL');
        $this->addSql('ALTER TABLE pago_canal ADD CONSTRAINT FK_23705BC1521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE pago_cuotas ADD CONSTRAINT FK_75D1048763FB8380 FOREIGN KEY (pago_id) REFERENCES pago (id)');
        $this->addSql('ALTER TABLE pago_cuotas ADD CONSTRAINT FK_75D104876A7CF079 FOREIGN KEY (cuota_id) REFERENCES cuota (id)');
        $this->addSql('ALTER TABLE pago_tipo CHANGE empresa_id empresa_id INT DEFAULT NULL, CHANGE orden orden INT DEFAULT NULL, CHANGE estado estado TINYINT(1) DEFAULT NULL, CHANGE is_boucher is_boucher TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE pago_tipo ADD CONSTRAINT FK_567222FB521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE pais CHANGE empresa_id empresa_id INT DEFAULT NULL, CHANGE orden orden INT DEFAULT NULL');
        $this->addSql('ALTER TABLE pais ADD CONSTRAINT FK_7E5D2EFF521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE privilegio CHANGE modulo_per_id modulo_per_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE privilegio ADD CONSTRAINT FK_D0E1EA51DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE privilegio ADD CONSTRAINT FK_D0E1EA513F4B5275 FOREIGN KEY (accion_id) REFERENCES accion (id)');
        $this->addSql('ALTER TABLE privilegio ADD CONSTRAINT FK_D0E1EA5188C77C8D FOREIGN KEY (modulo_per_id) REFERENCES modulo_per (id)');
        $this->addSql('ALTER TABLE privilegio_tipousuario CHANGE modulo_per_id modulo_per_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE privilegio_tipousuario ADD CONSTRAINT FK_BE31D90E3F4B5275 FOREIGN KEY (accion_id) REFERENCES accion (id)');
        $this->addSql('ALTER TABLE privilegio_tipousuario ADD CONSTRAINT FK_BE31D90E74CA5DCD FOREIGN KEY (tipousuario_id) REFERENCES usuario_tipo (id)');
        $this->addSql('ALTER TABLE privilegio_tipousuario ADD CONSTRAINT FK_BE31D90E88C77C8D FOREIGN KEY (modulo_per_id) REFERENCES modulo_per (id)');
        $this->addSql('ALTER TABLE reset_password_request CHANGE user_id user_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE reunion CHANGE empresa_id empresa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE reunion ADD CONSTRAINT FK_5B00A482521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE situacion_laboral CHANGE empresa_id empresa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE situacion_laboral ADD CONSTRAINT FK_7F28676521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE sucursal CHANGE cuenta_id cuenta_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE sucursal ADD CONSTRAINT FK_E99C6D569AEFF118 FOREIGN KEY (cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE ticket ADD ticket_tipo_id INT DEFAULT NULL, ADD fecha_ultima_gestion DATETIME DEFAULT NULL, CHANGE importancia_id importancia_id INT DEFAULT NULL, CHANGE destino_id destino_id INT DEFAULT NULL, CHANGE encargado_id encargado_id INT DEFAULT NULL, CHANGE motivo motivo VARCHAR(500) DEFAULT NULL, CHANGE respuesta respuesta VARCHAR(200) DEFAULT NULL, CHANGE detalle_cierre detalle_cierre VARCHAR(200) DEFAULT NULL, CHANGE fecha_asignado fecha_asignado DATETIME DEFAULT NULL, CHANGE fecha_respuesta fecha_respuesta DATETIME DEFAULT NULL, CHANGE fecha_cierre fecha_cierre DATETIME DEFAULT NULL, CHANGE estado_id estado_id INT DEFAULT NULL, CHANGE folio_sac folio_sac VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA370AE7BF1 FOREIGN KEY (contrato_id) REFERENCES contrato (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA393529ECD FOREIGN KEY (origen_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3E4360615 FOREIGN KEY (destino_id) REFERENCES usuario_tipo (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA34D75585E FOREIGN KEY (encargado_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA39F5A440B FOREIGN KEY (estado_id) REFERENCES ticket_estado (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3A5EB373E FOREIGN KEY (ticket_tipo_id) REFERENCES ticket_tipo (id)');
        $this->addSql('CREATE INDEX IDX_97A0ADA3A5EB373E ON ticket (ticket_tipo_id)');
        $this->addSql('ALTER TABLE ticket_estado CHANGE icon icon VARCHAR(255) DEFAULT NULL, CHANGE color color VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE ticket_historial CHANGE observacion observacion VARCHAR(400) NOT NULL, CHANGE estado_id estado_id INT DEFAULT NULL, CHANGE fecha fecha DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE ticket_historial ADD CONSTRAINT FK_BCAFDC18700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id)');
        $this->addSql('ALTER TABLE ticket_historial ADD CONSTRAINT FK_BCAFDC181EEFD20 FOREIGN KEY (usuario_registro_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE ticket_historial ADD CONSTRAINT FK_BCAFDC189F5A440B FOREIGN KEY (estado_id) REFERENCES ticket_estado (id)');
        $this->addSql('ALTER TABLE usuario CHANGE nombre nombre VARCHAR(100) NOT NULL, CHANGE empresa_actual empresa_actual INT DEFAULT NULL, CHANGE categoria_id categoria_id INT DEFAULT NULL, CHANGE status_id status_id INT DEFAULT NULL, CHANGE fecha_no_disponible fecha_no_disponible DATETIME DEFAULT NULL, CHANGE whatsapp whatsapp VARCHAR(255) DEFAULT NULL, CHANGE telefono telefono VARCHAR(255) DEFAULT NULL, CHANGE rut rut VARCHAR(255) DEFAULT NULL, CHANGE direccion direccion VARCHAR(255) DEFAULT NULL, CHANGE sexo sexo VARCHAR(255) DEFAULT NULL, CHANGE tipo_documento_id tipo_documento_id INT DEFAULT NULL, CHANGE color color VARCHAR(255) DEFAULT NULL, CHANGE password_ant password_ant VARCHAR(255) DEFAULT NULL, CHANGE lunes lunes TINYINT(1) DEFAULT NULL, CHANGE lunes_start lunes_start TIME DEFAULT NULL, CHANGE lunes_end lunes_end TIME DEFAULT NULL, CHANGE martes martes TINYINT(1) DEFAULT NULL, CHANGE martes_start martes_start TIME DEFAULT NULL, CHANGE martes_end martes_end TIME DEFAULT NULL, CHANGE miercoles miercoles TINYINT(1) DEFAULT NULL, CHANGE miercoles_start miercoles_start TIME DEFAULT NULL, CHANGE miercoles_end miercoles_end TIME DEFAULT NULL, CHANGE jueves jueves TINYINT(1) DEFAULT NULL, CHANGE jueves_start jueves_start TIME DEFAULT NULL, CHANGE jueves_end jueves_end TIME DEFAULT NULL, CHANGE viernes viernes TINYINT(1) DEFAULT NULL, CHANGE viernes_start viernes_start TIME DEFAULT NULL, CHANGE viernes_end viernes_end TIME DEFAULT NULL, CHANGE sabado sabado TINYINT(1) DEFAULT NULL, CHANGE sabado_start sabado_start TIME DEFAULT NULL, CHANGE sabado_end sabado_end TIME DEFAULT NULL, CHANGE domingo domingo TINYINT(1) DEFAULT NULL, CHANGE domingo_start domingo_start TIME DEFAULT NULL, CHANGE domingo_end domingo_end TIME DEFAULT NULL, CHANGE sobrecupo sobrecupo INT DEFAULT NULL, CHANGE lotes lotes JSON DEFAULT NULL, CHANGE fecha_nacimiento fecha_nacimiento DATE DEFAULT NULL, CHANGE fecha_aviso fecha_aviso DATE DEFAULT NULL, CHANGE estado_cartera estado_cartera TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE usuario ADD CONSTRAINT FK_2265B05DD001C42B FOREIGN KEY (usuario_tipo_id) REFERENCES usuario_tipo (id)');
        $this->addSql('ALTER TABLE usuario ADD CONSTRAINT FK_2265B05D3397707A FOREIGN KEY (categoria_id) REFERENCES usuario_categoria (id)');
        $this->addSql('ALTER TABLE usuario ADD CONSTRAINT FK_2265B05D6BF700BD FOREIGN KEY (status_id) REFERENCES usuario_status (id)');
        $this->addSql('ALTER TABLE usuario ADD CONSTRAINT FK_2265B05DF6939175 FOREIGN KEY (tipo_documento_id) REFERENCES usuario_tipo_documento (id)');
        $this->addSql('CREATE INDEX IDX_2265B05DF6939175 ON usuario (tipo_documento_id)');
        $this->addSql('ALTER TABLE usuario_cartera ADD CONSTRAINT FK_935338ABDB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE usuario_cartera ADD CONSTRAINT FK_935338ABA5A18135 FOREIGN KEY (cartera_id) REFERENCES cartera (id)');
        $this->addSql('ALTER TABLE usuario_categoria ADD CONSTRAINT FK_C72BF83F521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE usuario_cuenta CHANGE cuenta_id cuenta_id INT DEFAULT NULL, CHANGE usuario_id usuario_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE usuario_cuenta ADD CONSTRAINT FK_CBD55CC69AEFF118 FOREIGN KEY (cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE usuario_cuenta ADD CONSTRAINT FK_CBD55CC6DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE usuario_grupo CHANGE grupo_id grupo_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE usuario_lote CHANGE usuario_id usuario_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE usuario_lote ADD CONSTRAINT FK_CCE488FDB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE usuario_lote ADD CONSTRAINT FK_CCE488FB172197C FOREIGN KEY (lote_id) REFERENCES lotes (id)');
        $this->addSql('ALTER TABLE usuario_no_disponible CHANGE usuario_id usuario_id INT DEFAULT NULL, CHANGE fecha_inicio fecha_inicio DATE DEFAULT NULL, CHANGE fecha_fin fecha_fin DATE DEFAULT NULL, CHANGE anio anio INT DEFAULT NULL, CHANGE mes mes INT DEFAULT NULL, CHANGE dia dia INT DEFAULT NULL');
        $this->addSql('ALTER TABLE usuario_no_disponible ADD CONSTRAINT FK_7C64E39CDB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE usuario_tipo CHANGE orden orden INT DEFAULT NULL, CHANGE menu_cabezera_id menu_cabezera_id INT DEFAULT NULL, CHANGE empresa_id empresa_id INT DEFAULT NULL, CHANGE statues statues LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\'');
        $this->addSql('ALTER TABLE usuario_tipo ADD CONSTRAINT FK_19576757975F194D FOREIGN KEY (menu_cabezera_id) REFERENCES menu_cabezera (id)');
        $this->addSql('ALTER TABLE usuario_tipo ADD CONSTRAINT FK_19576757521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE usuario_usuariocategoria CHANGE cuenta_id cuenta_id INT DEFAULT NULL, CHANGE agenda_id agenda_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE usuario_usuariocategoria ADD CONSTRAINT FK_892F60F1DB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id)');
        $this->addSql('ALTER TABLE usuario_usuariocategoria ADD CONSTRAINT FK_892F60F19AEFF118 FOREIGN KEY (cuenta_id) REFERENCES cuenta (id)');
        $this->addSql('ALTER TABLE usuario_usuariocategoria ADD CONSTRAINT FK_892F60F1EA67784A FOREIGN KEY (agenda_id) REFERENCES agenda (id)');
        $this->addSql('ALTER TABLE usuario_usuariocategoria RENAME INDEX usuario_id TO IDX_892F60F1DB38439E');
        $this->addSql('ALTER TABLE usuario_usuariocategoria RENAME INDEX cuenta_id TO IDX_892F60F19AEFF118');
        $this->addSql('ALTER TABLE usuario_usuariocategoria RENAME INDEX agenda_id TO IDX_892F60F1EA67784A');
        $this->addSql('ALTER TABLE vencimiento CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE empresa_id empresa_id INT DEFAULT NULL, CHANGE val_min val_min INT DEFAULT NULL, CHANGE val_max val_max INT DEFAULT NULL, CHANGE color color VARCHAR(255) DEFAULT NULL, CHANGE icono icono VARCHAR(255) DEFAULT NULL, CHANGE monto_max monto_max INT DEFAULT NULL, CHANGE solo_por_admin solo_por_admin TINYINT(1) DEFAULT NULL, CHANGE nombre nombre VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE vencimiento ADD CONSTRAINT FK_66923AA8521E1991 FOREIGN KEY (empresa_id) REFERENCES empresa (id)');
        $this->addSql('ALTER TABLE webhook CHANGE verify_token verify_token VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE actuacion_anexo_procesal DROP FOREIGN KEY FK_7C63AABB94FD6108');
        $this->addSql('ALTER TABLE detalle_cuaderno DROP FOREIGN KEY FK_8FB7FE1494FD6108');
        $this->addSql('ALTER TABLE actuacion_anexo_procesal DROP FOREIGN KEY FK_7C63AABB223672E3');
        $this->addSql('ALTER TABLE detalle_cuaderno DROP FOREIGN KEY FK_8FB7FE14223672E3');
        $this->addSql('ALTER TABLE actuacion DROP FOREIGN KEY FK_321583D3EE4BC97C');
        $this->addSql('ALTER TABLE detalle_cuaderno DROP FOREIGN KEY FK_8FB7FE14EE4BC97C');
        $this->addSql('ALTER TABLE causa_observacion DROP FOREIGN KEY FK_23D9D014A254240F');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA3A5EB373E');
        $this->addSql('CREATE TABLE html_tempaltes (id INT AUTO_INCREMENT NOT NULL, tipo VARCHAR(45) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, html_template TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE logs (id INT AUTO_INCREMENT NOT NULL, log_id INT DEFAULT NULL, log_date DATETIME DEFAULT \'NULL\', log_message VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE mails_enviados (id INT AUTO_INCREMENT NOT NULL, tipo_envio_id INT DEFAULT NULL, fecha_enviado DATETIME DEFAULT \'NULL\', contrato_id INT DEFAULT NULL, pago_cuota_id INT DEFAULT NULL, pago_id INT DEFAULT NULL, cuota_id INT DEFAULT NULL, estado INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('DROP TABLE actuacion');
        $this->addSql('DROP TABLE actuacion_anexo_procesal');
        $this->addSql('DROP TABLE anexo_procesal');
        $this->addSql('DROP TABLE contrato_casetracking');
        $this->addSql('DROP TABLE contrato_tramitador');
        $this->addSql('DROP TABLE cuaderno');
        $this->addSql('DROP TABLE detalle_cuaderno');
        $this->addSql('DROP TABLE movatec_log');
        $this->addSql('DROP TABLE primera_cuota');
        $this->addSql('DROP TABLE producto');
        $this->addSql('DROP TABLE reportes');
        $this->addSql('DROP TABLE ticket_tipo');
        $this->addSql('DROP TABLE vw_causas_activas_final');
        $this->addSql('DROP TABLE vw_clientes_activos_final');
        $this->addSql('DROP TABLE vw_contrato');
        $this->addSql('DROP TABLE vw_resumen_causas');
        $this->addSql('ALTER TABLE accion CHANGE empresa_id empresa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE agenda DROP FOREIGN KEY FK_2CEDC87768DB5B2E');
        $this->addSql('ALTER TABLE agenda CHANGE cuenta_id cuenta_id INT DEFAULT NULL, CHANGE gestionar_id gestionar_id INT DEFAULT NULL, CHANGE agendador_id agendador_id INT DEFAULT NULL, CHANGE sucursal_id sucursal_id INT DEFAULT NULL, CHANGE status_id status_id INT DEFAULT NULL, CHANGE abogado_id abogado_id INT DEFAULT NULL, CHANGE reunion_id reunion_id INT DEFAULT NULL, CHANGE agenda_contacto_id agenda_contacto_id INT DEFAULT NULL, CHANGE sub_status_id sub_status_id INT DEFAULT NULL, CHANGE canal_id canal_id INT DEFAULT NULL, CHANGE nombre_cliente nombre_cliente VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE email_cliente email_cliente VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE telefono_cliente telefono_cliente VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ciudad_cliente ciudad_cliente VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE fecha_carga fecha_carga DATETIME DEFAULT \'NULL\', CHANGE fecha_asignado fecha_asignado DATETIME DEFAULT \'NULL\', CHANGE monto monto NUMERIC(10, 0) DEFAULT \'NULL\', CHANGE rut_cliente rut_cliente VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE telefono_recado_cliente telefono_recado_cliente VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE fecha_contrato fecha_contrato DATETIME DEFAULT \'NULL\', CHANGE lead lead VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE form_id form_id VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE pago_actual pago_actual NUMERIC(10, 0) DEFAULT \'NULL\', CHANGE fecha_seguimiento fecha_seguimiento DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE agenda RENAME INDEX idx_2cedc8776bf700bd TO FK_2CEDC8776BF700BD');
        $this->addSql('ALTER TABLE agenda RENAME INDEX idx_2cedc87779fa4603 TO FK_2CEDC87779FA4603');
        $this->addSql('ALTER TABLE agenda_observacion CHANGE status_id status_id INT DEFAULT NULL, CHANGE sub_status_id sub_status_id INT DEFAULT NULL, CHANGE abogado_destino_id abogado_destino_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE agenda_observacion RENAME INDEX idx_bb645400cf6bbc1e TO FK_BB645400CF6BBC1E');
        $this->addSql('ALTER TABLE agenda_observacion RENAME INDEX idx_bb64540079fa4603 TO FK_BB64540079FA4603');
        $this->addSql('ALTER TABLE agenda_status CHANGE orden orden INT DEFAULT NULL, CHANGE icon icon VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE color color VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE vermas vermas TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE agenda_sub_status CHANGE agenda_status_id agenda_status_id INT DEFAULT NULL, CHANGE color color VARCHAR(10) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE causa DROP FOREIGN KEY FK_F7B7BBA6516A508C');
        $this->addSql('ALTER TABLE causa DROP FOREIGN KEY FK_F7B7BBA6AABE9B97');
        $this->addSql('ALTER TABLE causa DROP FOREIGN KEY FK_F7B7BBA6EA67784A');
        $this->addSql('ALTER TABLE causa DROP causa_finalizada, DROP fecha_finalizado, CHANGE materia_estrategia_id materia_estrategia_id INT NOT NULL, CHANGE juzgado_cuenta_id juzgado_cuenta_id INT DEFAULT NULL, CHANGE anexo_id anexo_id INT DEFAULT NULL, CHANGE id_causa id_causa VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE causa_nombre causa_nombre VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE estado estado TINYINT(1) DEFAULT \'NULL\', CHANGE fecha_ultimo_ingreso fecha_ultimo_ingreso DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE causa RENAME INDEX idx_f7b7bba6c9348664 TO FK_F7B7BBA6C9348664');
        $this->addSql('DROP INDEX IDX_23D9D014A254240F ON causa_observacion');
        $this->addSql('ALTER TABLE causa_observacion DROP detalle_cuaderno_id, CHANGE causa_id causa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ciudad CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE ciudad RENAME INDEX idx_8e86059e98260155 TO region_id');
        $this->addSql('ALTER TABLE cliente_potencial CHANGE form_id form_id DOUBLE PRECISION DEFAULT \'NULL\', CHANGE leadgen_id leadgen_id DOUBLE PRECISION DEFAULT \'NULL\', CHANGE page_id page_id DOUBLE PRECISION DEFAULT \'NULL\', CHANGE created_time created_time DOUBLE PRECISION DEFAULT \'NULL\', CHANGE campos campos LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`');
        $this->addSql('ALTER TABLE cobranza DROP FOREIGN KEY FK_AE20EF3D70AE7BF1');
        $this->addSql('DROP INDEX IDX_AE20EF3D70AE7BF1 ON cobranza');
        $this->addSql('ALTER TABLE cobranza ADD cuota_id INT DEFAULT NULL, CHANGE funcion_id funcion_id INT DEFAULT NULL, CHANGE respuesta_id respuesta_id INT DEFAULT NULL, CHANGE fecha_compromiso fecha_compromiso DATETIME DEFAULT \'NULL\', CHANGE is_nulo is_nulo TINYINT(1) DEFAULT \'NULL\', CHANGE fecha fecha DATE DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE cobranza_respuesta CHANGE is_fecha_compromiso is_fecha_compromiso TINYINT(1) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE comuna DROP FOREIGN KEY FK_7E7DAE49E8608214');
        $this->addSql('ALTER TABLE comuna CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE comuna ADD CONSTRAINT comuna_ibfk_1 FOREIGN KEY (ciudad_id) REFERENCES comuna (id)');
        $this->addSql('ALTER TABLE comuna RENAME INDEX idx_7e7dae49e8608214 TO ciudad_id');
        $this->addSql('ALTER TABLE configuracion CHANGE host host VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE lotes lotes INT DEFAULT NULL, CHANGE valor_multa valor_multa INT DEFAULT NULL, CHANGE toku_id toku_id VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE toku_secret toku_secret VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE contrato DROP INDEX UNIQ_666965236FEFB00C, ADD INDEX FK_666965236FEFB00C (id_lote_id)');
        $this->addSql('ALTER TABLE contrato DROP FOREIGN KEY FK_666965236FEFB00C');
        $this->addSql('ALTER TABLE contrato CHANGE estado_civil_id estado_civil_id INT DEFAULT NULL, CHANGE situacion_laboral_id situacion_laboral_id INT DEFAULT NULL, CHANGE estrategia_juridica_id estrategia_juridica_id INT DEFAULT NULL, CHANGE escritura_id escritura_id INT DEFAULT NULL, CHANGE agenda_id agenda_id INT DEFAULT NULL, CHANGE sucursal_id sucursal_id INT DEFAULT NULL, CHANGE tramitador_id tramitador_id INT DEFAULT NULL, CHANGE cliente_id cliente_id INT DEFAULT NULL, CHANGE pais_id pais_id INT DEFAULT NULL, CHANGE vehiculo_id vehiculo_id INT DEFAULT NULL, CHANGE vivienda_id vivienda_id INT DEFAULT NULL, CHANGE reunion_id reunion_id INT DEFAULT NULL, CHANGE id_lote_id id_lote_id INT DEFAULT NULL, CHANGE ccomuna_id ccomuna_id INT DEFAULT NULL, CHANGE cciudad_id cciudad_id INT DEFAULT NULL, CHANGE cregion_id cregion_id INT DEFAULT NULL, CHANGE cartera_id cartera_id INT DEFAULT NULL, CHANGE grupo_id grupo_id INT DEFAULT NULL, CHANGE estado_encuesta_id estado_encuesta_id INT DEFAULT NULL, CHANGE email email VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE ciudad ciudad VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE rut rut VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE comuna comuna VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE titulo_contrato titulo_contrato VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE monto_nivel_deuda monto_nivel_deuda NUMERIC(10, 0) DEFAULT \'NULL\', CHANGE monto_contrato monto_contrato NUMERIC(10, 0) DEFAULT \'NULL\', CHANGE cuotas cuotas INT DEFAULT NULL, CHANGE valor_cuota valor_cuota NUMERIC(10, 0) DEFAULT \'NULL\', CHANGE interes interes NUMERIC(5, 2) DEFAULT \'NULL\', CHANGE dia_pago dia_pago INT DEFAULT NULL, CHANGE fecha_creacion fecha_creacion DATETIME DEFAULT \'NULL\', CHANGE clave_unica clave_unica VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE telefono_recado telefono_recado VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE fecha_primer_pago fecha_primer_pago DATETIME DEFAULT \'NULL\', CHANGE primera_cuota primera_cuota DOUBLE PRECISION DEFAULT \'NULL\', CHANGE fecha_primera_cuota fecha_primera_cuota DATE DEFAULT \'NULL\', CHANGE pdf pdf VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE is_abono is_abono TINYINT(1) DEFAULT \'NULL\', CHANGE fecha_ultimo_pago fecha_ultimo_pago DATE DEFAULT \'NULL\', CHANGE is_finalizado is_finalizado TINYINT(1) DEFAULT \'NULL\', CHANGE lote lote INT DEFAULT NULL, CHANGE pdf_termino pdf_termino VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE fecha_termino fecha_termino DATETIME DEFAULT \'NULL\', CHANGE vigencia vigencia INT DEFAULT NULL, CHANGE fecha_desiste fecha_desiste DATETIME DEFAULT \'NULL\', CHANGE fecha_pdf_anexo fecha_pdf_anexo DATETIME DEFAULT \'NULL\', CHANGE ultima_funcion ultima_funcion VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE q_mov q_mov INT DEFAULT NULL, CHANGE fecha_compromiso fecha_compromiso DATE DEFAULT \'NULL\', CHANGE folio folio VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE sexo sexo VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE is_anexo is_anexo TINYINT(1) DEFAULT \'NULL\', CHANGE proximo_vencimiento proximo_vencimiento DATE DEFAULT \'NULL\', CHANGE fecha_ultima_gestion fecha_ultima_gestion DATE DEFAULT \'NULL\', CHANGE pago_actual pago_actual NUMERIC(10, 0) DEFAULT \'NULL\', CHANGE is_total is_total TINYINT(1) DEFAULT \'NULL\', CHANGE is_incorporacion is_incorporacion TINYINT(1) DEFAULT \'NULL\', CHANGE observacion_encuesta observacion_encuesta VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE fecha_encuesta fecha_encuesta DATETIME DEFAULT \'NULL\', CHANGE qty_encuesta qty_encuesta INT DEFAULT 0, CHANGE qty_gestion_encuesta qty_gestion_encuesta INT DEFAULT NULL');
        $this->addSql('ALTER TABLE contrato ADD CONSTRAINT FK_666965236FEFB00C FOREIGN KEY (id_lote_id) REFERENCES lotes (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE contrato RENAME INDEX idx_66696523279a5d5e TO FK_66696523279A5D5E');
        $this->addSql('ALTER TABLE contrato RENAME INDEX idx_666965237c88a2f6 TO FK_666965237C88A2F6');
        $this->addSql('ALTER TABLE contrato RENAME INDEX idx_66696523a5a18135 TO FK_66696523A5A18135');
        $this->addSql('ALTER TABLE contrato_anexo DROP FOREIGN KEY FK_9DD8C30E1EEFD20');
        $this->addSql('DROP INDEX IDX_9DD8C30E1EEFD20 ON contrato_anexo');
        $this->addSql('ALTER TABLE contrato_anexo DROP usuario_registro_id, CHANGE pdf pdf VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE folio folio INT DEFAULT NULL, CHANGE monto_contrato monto_contrato DOUBLE PRECISION DEFAULT \'NULL\', CHANGE is_abono is_abono TINYINT(1) DEFAULT \'NULL\', CHANGE abono abono DOUBLE PRECISION DEFAULT \'NULL\', CHANGE is_total is_total TINYINT(1) DEFAULT \'NULL\', CHANGE n_cuotas n_cuotas INT DEFAULT NULL, CHANGE valor_cuota valor_cuota DOUBLE PRECISION DEFAULT \'NULL\', CHANGE dias_pago dias_pago INT DEFAULT NULL, CHANGE fecha_primer_pago fecha_primer_pago DATE DEFAULT \'NULL\', CHANGE vigencia vigencia INT DEFAULT NULL, CHANGE tipo_anexo tipo_anexo SMALLINT DEFAULT NULL, CHANGE estado estado TINYINT(1) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE contrato_archivos CHANGE causa_id causa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE contrato_mee CHANGE mee_id mee_id INT DEFAULT NULL, CHANGE mees mees LONGTEXT CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:array)\'');
        $this->addSql('ALTER TABLE contrato_observacion DROP FOREIGN KEY FK_1AA2E2DE1EEFD20');
        $this->addSql('ALTER TABLE contrato_observacion DROP FOREIGN KEY FK_1AA2E2DE70AE7BF1');
        $this->addSql('ALTER TABLE contrato_rol CHANGE juzgado_id juzgado_id INT DEFAULT NULL, CHANGE contrato_id contrato_id INT DEFAULT NULL, CHANGE nombre_rol nombre_rol VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE contrato_vehiculo CHANGE empresa_id empresa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE contrato_vivienda CHANGE empresa_id empresa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE cuenta CHANGE fecha_ultimamodificacion fecha_ultimamodificacion DATETIME DEFAULT \'NULL\', CHANGE page_id page_id DOUBLE PRECISION DEFAULT \'NULL\', CHANGE vigencia_contratos vigencia_contratos INT DEFAULT NULL');
        $this->addSql('ALTER TABLE cuenta_materia CHANGE estado estado TINYINT(1) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE cuota CHANGE usuario_anulacion_id usuario_anulacion_id INT DEFAULT NULL, CHANGE anexo_id anexo_id INT DEFAULT NULL, CHANGE pagado pagado INT DEFAULT NULL, CHANGE anular anular TINYINT(1) DEFAULT \'NULL\', CHANGE fecha_anulacion fecha_anulacion DATETIME DEFAULT \'NULL\', CHANGE is_multa is_multa TINYINT(1) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE empresa CHANGE rol rol VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE logo logo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE fecha_ultimamodificacion fecha_ultimamodificacion DATETIME DEFAULT \'NULL\', CHANGE logo_alt logo_alt VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE encuesta DROP FOREIGN KEY FK_B25B68419F5A440B');
        $this->addSql('DROP INDEX IDX_B25B68419F5A440B ON encuesta');
        $this->addSql('ALTER TABLE encuesta CHANGE funcion_encuesta_id funcion_encuesta_id INT DEFAULT NULL, CHANGE funcion_respuesta_id funcion_respuesta_id INT DEFAULT NULL, CHANGE fecha_creacion fecha_creacion DATETIME DEFAULT \'NULL\', CHANGE fecha_pendiente fecha_pendiente DATETIME DEFAULT \'NULL\', CHANGE fecha_cierre fecha_cierre DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE encuesta_preguntas CHANGE nota nota VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE respuesta_abierta respuesta_abierta VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE escritura CHANGE empresa_id empresa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE estado_civil CHANGE empresa_id empresa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE estrategia_juridica CHANGE empresa_id empresa_id INT DEFAULT NULL, CHANGE linea_tiempo_id linea_tiempo_id INT DEFAULT NULL, CHANGE precio precio DOUBLE PRECISION DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE importacion CHANGE cuenta_id cuenta_id INT DEFAULT NULL, CHANGE usuario_carga_id usuario_carga_id INT DEFAULT NULL, CHANGE estado estado INT DEFAULT NULL, CHANGE tipo_importacion tipo_importacion INT DEFAULT NULL');
        $this->addSql('ALTER TABLE juzgado DROP FOREIGN KEY FK_695F140E521E1991');
        $this->addSql('ALTER TABLE juzgado CHANGE empresa_id empresa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE juzgado RENAME INDEX idx_695f140e521e1991 TO empresa_id');
        $this->addSql('ALTER TABLE juzgado_cuenta DROP FOREIGN KEY FK_FCE1830F9AEFF118');
        $this->addSql('ALTER TABLE juzgado_cuenta DROP FOREIGN KEY FK_FCE1830FB9A57363');
        $this->addSql('ALTER TABLE linea_tiempo CHANGE orden orden INT DEFAULT NULL');
        $this->addSql('ALTER TABLE linea_tiempo_etapas DROP FOREIGN KEY FK_6535CAFD63AA8B75');
        $this->addSql('ALTER TABLE linea_tiempo_terminada DROP FOREIGN KEY FK_271DA87BE980B549');
        $this->addSql('ALTER TABLE linea_tiempo_terminada DROP FOREIGN KEY FK_271DA87BBCFBDE31');
        $this->addSql('ALTER TABLE linea_tiempo_terminada DROP FOREIGN KEY FK_271DA87B1EEFD20');
        $this->addSql('ALTER TABLE lotes DROP FOREIGN KEY FK_7BDBF5EC521E1991');
        $this->addSql('ALTER TABLE lotes CHANGE empresa_id empresa_id INT DEFAULT NULL, CHANGE is_asignado is_asignado TINYINT(1) DEFAULT \'0\' NOT NULL');
        $this->addSql('ALTER TABLE materia DROP FOREIGN KEY FK_6DF05284521E1991');
        $this->addSql('ALTER TABLE materia_estrategia DROP FOREIGN KEY FK_8A1D519EB54DBBCB');
        $this->addSql('ALTER TABLE materia_estrategia DROP FOREIGN KEY FK_8A1D519E62144410');
        $this->addSql('ALTER TABLE mee DROP FOREIGN KEY FK_9A1C8B54516A508C');
        $this->addSql('ALTER TABLE mee DROP FOREIGN KEY FK_9A1C8B545D855194');
        $this->addSql('ALTER TABLE mensaje DROP FOREIGN KEY FK_9B631D013F7A1974');
        $this->addSql('ALTER TABLE mensaje DROP FOREIGN KEY FK_9B631D011EEFD20');
        $this->addSql('ALTER TABLE mensaje DROP FOREIGN KEY FK_9B631D0117064CB7');
        $this->addSql('ALTER TABLE mensaje CHANGE usuario_registro_id usuario_registro_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE mensaje_tipo MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE mensaje_tipo DROP PRIMARY KEY');
        $this->addSql('ALTER TABLE mensaje_tipo CHANGE id id INT NOT NULL');
        $this->addSql('ALTER TABLE menu DROP FOREIGN KEY FK_7D053A93521E1991');
        $this->addSql('ALTER TABLE menu DROP FOREIGN KEY FK_7D053A93A53F971C');
        $this->addSql('ALTER TABLE menu DROP FOREIGN KEY FK_7D053A93975F194D');
        $this->addSql('ALTER TABLE menu DROP FOREIGN KEY FK_7D053A93C07F55F5');
        $this->addSql('ALTER TABLE menu CHANGE depende_de_id depende_de_id INT DEFAULT NULL, CHANGE menu_cabezera_id menu_cabezera_id INT DEFAULT NULL, CHANGE modulo_id modulo_id INT DEFAULT NULL, CHANGE icono icono VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE orden orden INT DEFAULT NULL');
        $this->addSql('ALTER TABLE menu_cabezera DROP FOREIGN KEY FK_431A2F13521E1991');
        $this->addSql('ALTER TABLE menu_cabezera CHANGE empresa_id empresa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE modulo CHANGE nombre_alt nombre_alt VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE descripcion descripcion VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE modulo_per DROP FOREIGN KEY FK_ABF22FE5521E1991');
        $this->addSql('ALTER TABLE modulo_per DROP FOREIGN KEY FK_ABF22FE5C07F55F5');
        $this->addSql('ALTER TABLE movimientospjud CHANGE fecha_pjud fecha_pjud DATE DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE pago DROP FOREIGN KEY FK_F4DF5F3EC6690F67');
        $this->addSql('ALTER TABLE pago DROP FOREIGN KEY FK_F4DF5F3EFF66CCC7');
        $this->addSql('ALTER TABLE pago DROP FOREIGN KEY FK_F4DF5F3E1EEFD20');
        $this->addSql('ALTER TABLE pago DROP FOREIGN KEY FK_F4DF5F3E1FB75A3B');
        $this->addSql('ALTER TABLE pago DROP FOREIGN KEY FK_F4DF5F3EBAF036CE');
        $this->addSql('ALTER TABLE pago DROP FOREIGN KEY FK_F4DF5F3E70AE7BF1');
        $this->addSql('ALTER TABLE pago ADD fecha_ingreso DATE DEFAULT \'NULL\', CHANGE usuario_anulacion_id usuario_anulacion_id INT DEFAULT NULL, CHANGE contrato_id contrato_id INT DEFAULT NULL, CHANGE boleta boleta VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE comprobante comprobante LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE ncomprobante ncomprobante VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE anulado anulado TINYINT(1) DEFAULT \'NULL\', CHANGE fecha_anulacion fecha_anulacion DATETIME DEFAULT \'NULL\'');
        $this->addSql('CREATE INDEX contrato_id_3 ON pago (contrato_id)');
        $this->addSql('CREATE INDEX contrato_id ON pago (contrato_id)');
        $this->addSql('ALTER TABLE pago RENAME INDEX idx_f4df5f3e70ae7bf1 TO contrato_id_2');
        $this->addSql('ALTER TABLE pago_canal DROP FOREIGN KEY FK_23705BC1521E1991');
        $this->addSql('ALTER TABLE pago_canal CHANGE empresa_id empresa_id INT DEFAULT NULL, CHANGE estado estado TINYINT(1) DEFAULT \'NULL\', CHANGE orden orden INT DEFAULT NULL');
        $this->addSql('ALTER TABLE pago_cuotas DROP FOREIGN KEY FK_75D1048763FB8380');
        $this->addSql('ALTER TABLE pago_cuotas DROP FOREIGN KEY FK_75D104876A7CF079');
        $this->addSql('ALTER TABLE pago_tipo DROP FOREIGN KEY FK_567222FB521E1991');
        $this->addSql('ALTER TABLE pago_tipo CHANGE empresa_id empresa_id INT DEFAULT NULL, CHANGE orden orden INT DEFAULT NULL, CHANGE estado estado TINYINT(1) DEFAULT \'NULL\', CHANGE is_boucher is_boucher TINYINT(1) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE pais DROP FOREIGN KEY FK_7E5D2EFF521E1991');
        $this->addSql('ALTER TABLE pais CHANGE empresa_id empresa_id INT DEFAULT NULL, CHANGE orden orden INT DEFAULT NULL');
        $this->addSql('ALTER TABLE privilegio DROP FOREIGN KEY FK_D0E1EA51DB38439E');
        $this->addSql('ALTER TABLE privilegio DROP FOREIGN KEY FK_D0E1EA513F4B5275');
        $this->addSql('ALTER TABLE privilegio DROP FOREIGN KEY FK_D0E1EA5188C77C8D');
        $this->addSql('ALTER TABLE privilegio CHANGE modulo_per_id modulo_per_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE privilegio_tipousuario DROP FOREIGN KEY FK_BE31D90E3F4B5275');
        $this->addSql('ALTER TABLE privilegio_tipousuario DROP FOREIGN KEY FK_BE31D90E74CA5DCD');
        $this->addSql('ALTER TABLE privilegio_tipousuario DROP FOREIGN KEY FK_BE31D90E88C77C8D');
        $this->addSql('ALTER TABLE privilegio_tipousuario CHANGE modulo_per_id modulo_per_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE reset_password_request DROP FOREIGN KEY FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE reset_password_request CHANGE user_id user_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE reunion DROP FOREIGN KEY FK_5B00A482521E1991');
        $this->addSql('ALTER TABLE reunion CHANGE empresa_id empresa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE situacion_laboral DROP FOREIGN KEY FK_7F28676521E1991');
        $this->addSql('ALTER TABLE situacion_laboral CHANGE empresa_id empresa_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE sucursal DROP FOREIGN KEY FK_E99C6D569AEFF118');
        $this->addSql('ALTER TABLE sucursal CHANGE cuenta_id cuenta_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA370AE7BF1');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA393529ECD');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA3E4360615');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA34D75585E');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA3521E1991');
        $this->addSql('ALTER TABLE ticket DROP FOREIGN KEY FK_97A0ADA39F5A440B');
        $this->addSql('DROP INDEX IDX_97A0ADA3A5EB373E ON ticket');
        $this->addSql('ALTER TABLE ticket DROP ticket_tipo_id, DROP fecha_ultima_gestion, CHANGE destino_id destino_id INT DEFAULT NULL, CHANGE encargado_id encargado_id INT DEFAULT NULL, CHANGE estado_id estado_id INT DEFAULT NULL, CHANGE importancia_id importancia_id INT DEFAULT NULL, CHANGE motivo motivo VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE respuesta respuesta VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE detalle_cierre detalle_cierre VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE fecha_asignado fecha_asignado DATETIME DEFAULT \'NULL\', CHANGE fecha_respuesta fecha_respuesta DATETIME DEFAULT \'NULL\', CHANGE fecha_cierre fecha_cierre DATETIME DEFAULT \'NULL\', CHANGE folio_sac folio_sac VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE ticket_estado CHANGE icon icon VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE color color VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE ticket_historial DROP FOREIGN KEY FK_BCAFDC18700047D2');
        $this->addSql('ALTER TABLE ticket_historial DROP FOREIGN KEY FK_BCAFDC181EEFD20');
        $this->addSql('ALTER TABLE ticket_historial DROP FOREIGN KEY FK_BCAFDC189F5A440B');
        $this->addSql('ALTER TABLE ticket_historial CHANGE estado_id estado_id INT DEFAULT NULL, CHANGE observacion observacion VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE fecha fecha DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE usuario DROP FOREIGN KEY FK_2265B05DD001C42B');
        $this->addSql('ALTER TABLE usuario DROP FOREIGN KEY FK_2265B05D3397707A');
        $this->addSql('ALTER TABLE usuario DROP FOREIGN KEY FK_2265B05D6BF700BD');
        $this->addSql('ALTER TABLE usuario DROP FOREIGN KEY FK_2265B05DF6939175');
        $this->addSql('DROP INDEX IDX_2265B05DF6939175 ON usuario');
        $this->addSql('ALTER TABLE usuario CHANGE categoria_id categoria_id INT DEFAULT NULL, CHANGE status_id status_id INT DEFAULT NULL, CHANGE tipo_documento_id tipo_documento_id INT DEFAULT NULL, CHANGE nombre nombre VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE empresa_actual empresa_actual INT DEFAULT NULL, CHANGE fecha_no_disponible fecha_no_disponible DATETIME DEFAULT \'NULL\', CHANGE whatsapp whatsapp VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE telefono telefono VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE rut rut VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE direccion direccion VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE sexo sexo VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE color color VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE password_ant password_ant VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE lunes lunes TINYINT(1) DEFAULT \'NULL\', CHANGE lunes_start lunes_start TIME DEFAULT \'NULL\', CHANGE lunes_end lunes_end TIME DEFAULT \'NULL\', CHANGE martes martes TINYINT(1) DEFAULT \'NULL\', CHANGE martes_start martes_start TIME DEFAULT \'NULL\', CHANGE martes_end martes_end TIME DEFAULT \'NULL\', CHANGE miercoles miercoles TINYINT(1) DEFAULT \'NULL\', CHANGE miercoles_start miercoles_start TIME DEFAULT \'NULL\', CHANGE miercoles_end miercoles_end TIME DEFAULT \'NULL\', CHANGE jueves jueves TINYINT(1) DEFAULT \'NULL\', CHANGE jueves_start jueves_start TIME DEFAULT \'NULL\', CHANGE jueves_end jueves_end TIME DEFAULT \'NULL\', CHANGE viernes viernes TINYINT(1) DEFAULT \'NULL\', CHANGE viernes_start viernes_start TIME DEFAULT \'NULL\', CHANGE viernes_end viernes_end TIME DEFAULT \'NULL\', CHANGE sabado sabado TINYINT(1) DEFAULT \'NULL\', CHANGE sabado_start sabado_start TIME DEFAULT \'NULL\', CHANGE sabado_end sabado_end TIME DEFAULT \'NULL\', CHANGE domingo domingo TINYINT(1) DEFAULT \'NULL\', CHANGE domingo_start domingo_start TIME DEFAULT \'NULL\', CHANGE domingo_end domingo_end TIME DEFAULT \'NULL\', CHANGE sobrecupo sobrecupo INT DEFAULT NULL, CHANGE lotes lotes LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE fecha_nacimiento fecha_nacimiento DATE DEFAULT \'NULL\', CHANGE fecha_aviso fecha_aviso DATE DEFAULT \'NULL\', CHANGE estado_cartera estado_cartera TINYINT(1) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE usuario_cartera DROP FOREIGN KEY FK_935338ABDB38439E');
        $this->addSql('ALTER TABLE usuario_cartera DROP FOREIGN KEY FK_935338ABA5A18135');
        $this->addSql('ALTER TABLE usuario_categoria DROP FOREIGN KEY FK_C72BF83F521E1991');
        $this->addSql('ALTER TABLE usuario_cuenta DROP FOREIGN KEY FK_CBD55CC69AEFF118');
        $this->addSql('ALTER TABLE usuario_cuenta DROP FOREIGN KEY FK_CBD55CC6DB38439E');
        $this->addSql('ALTER TABLE usuario_cuenta CHANGE cuenta_id cuenta_id INT DEFAULT NULL, CHANGE usuario_id usuario_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE usuario_grupo CHANGE grupo_id grupo_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE usuario_lote DROP FOREIGN KEY FK_CCE488FDB38439E');
        $this->addSql('ALTER TABLE usuario_lote DROP FOREIGN KEY FK_CCE488FB172197C');
        $this->addSql('ALTER TABLE usuario_lote CHANGE usuario_id usuario_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE usuario_no_disponible DROP FOREIGN KEY FK_7C64E39CDB38439E');
        $this->addSql('ALTER TABLE usuario_no_disponible CHANGE usuario_id usuario_id INT DEFAULT NULL, CHANGE fecha_inicio fecha_inicio DATE DEFAULT \'NULL\', CHANGE fecha_fin fecha_fin DATE DEFAULT \'NULL\', CHANGE anio anio INT DEFAULT NULL, CHANGE mes mes INT DEFAULT NULL, CHANGE dia dia INT DEFAULT NULL');
        $this->addSql('ALTER TABLE usuario_tipo DROP FOREIGN KEY FK_19576757975F194D');
        $this->addSql('ALTER TABLE usuario_tipo DROP FOREIGN KEY FK_19576757521E1991');
        $this->addSql('ALTER TABLE usuario_tipo CHANGE menu_cabezera_id menu_cabezera_id INT DEFAULT NULL, CHANGE empresa_id empresa_id INT DEFAULT NULL, CHANGE orden orden INT DEFAULT NULL, CHANGE statues statues LONGTEXT CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:array)\'');
        $this->addSql('ALTER TABLE usuario_usuariocategoria DROP FOREIGN KEY FK_892F60F1DB38439E');
        $this->addSql('ALTER TABLE usuario_usuariocategoria DROP FOREIGN KEY FK_892F60F19AEFF118');
        $this->addSql('ALTER TABLE usuario_usuariocategoria DROP FOREIGN KEY FK_892F60F1EA67784A');
        $this->addSql('ALTER TABLE usuario_usuariocategoria CHANGE cuenta_id cuenta_id INT DEFAULT NULL, CHANGE agenda_id agenda_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE usuario_usuariocategoria RENAME INDEX idx_892f60f19aeff118 TO cuenta_id');
        $this->addSql('ALTER TABLE usuario_usuariocategoria RENAME INDEX idx_892f60f1ea67784a TO agenda_id');
        $this->addSql('ALTER TABLE usuario_usuariocategoria RENAME INDEX idx_892f60f1db38439e TO usuario_id');
        $this->addSql('ALTER TABLE vencimiento DROP FOREIGN KEY FK_66923AA8521E1991');
        $this->addSql('ALTER TABLE vencimiento CHANGE id id INT NOT NULL, CHANGE empresa_id empresa_id INT DEFAULT NULL, CHANGE val_min val_min INT DEFAULT NULL, CHANGE val_max val_max INT DEFAULT NULL, CHANGE color color VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE icono icono VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE nombre nombre VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE monto_max monto_max INT DEFAULT NULL, CHANGE solo_por_admin solo_por_admin TINYINT(1) DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE webhook CHANGE verify_token verify_token VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
    }
}
